### ISSUE TITLE
Allow to use native WebSocket API with the plugin

### ISSUE THREAD

**Issue by coco1979ka** [coco1979ka/cypress-websocket-plugin#19]
Currently the plugin does not support using the native WebSocket API. In order to support new projects, we need to investigate, how we can make it work with the native API. 

Todos:
- Find a way to make it work with the native WebSocket API
- Documentation
- Use native API in the Cypress tests

**Comment by InTheZ** [comment]
That one-line change from win.MockedWebSocket to win.WebSocket has the native web sockets working on my project. It could be that you can do both and have rxjs and native working on the same code base.

**Comment by coco1979ka** [comment]
Ok, but Cypress is also using web sockets for internal communication. If I replace win.WebSocket with the mock implementation, Cypress also loses the connection (you will get a lot of errors in the console - the tests as far as I can tell are running anyway).
I had the idea anyway to allow to specify the name of the mocked web socket property - it could even default to win.WebSocket. However, I have to check if the mocking still works like intended.
