### ISSUE TITLE
Use of topics in websockets

### ISSUE THREAD

**Issue by zereperez01** [coco1979ka/cypress-websocket-plugin#32]
Does this plugin support the use of topic to the communication?
 If so, how do you configure to listen an send messages?

**Comment by coco1979ka** [comment]
Can you tell me what Library use to realize topics? If you're using socket.io there is no support yet.

**Comment by zereperez01** [comment]
No, it was rxjs.

**Comment by zereperez01** [comment]
To generate websockets and define topics is through spring-boot-starter-websocket

**Comment by zereperez01** [comment]
And in the frontend we use this:

import { Injectable } from '@angular/core';
import { RxStomp, RxStompConfig } from '@stomp/rx-stomp';

**Comment by coco1979ka** [comment]
Ah ok, this is about stomp. This is not supported right now, but basically it is just a protocol on top of websockets, so you might be able to implement it manually.
